# Generated by Django 4.2.1 on 2023-06-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='desription',
            new_name='description',
        ),
    ]
